# Benchmark Report: Mistral Large 3

**Date:** 2026-02-08 09:44:27 UTC
**Model ID:** mistral.mistral-large-3-675b-instruct
**Provider:** Mistral AI

## Pricing

| Metric | Cost per 1M tokens |
|--------|-------------------|
| Input | $0.50 |
| Output | $1.50 |

## Results Summary

| Metric | Value |
|--------|-------|
| Total Tests | 33 |
| Passed | 32 |
| Failed | 1 |
| Critical Failures | 0 |
| Pass Rate | **97%** |

## Test Details

| Test | Status | Duration | Notes |
|------|--------|----------|-------|
| Clawdbot Verification | ✅ PASS | 6s | |
| Basic Chat | ✅ PASS | 6s | |
| Tool Use Response | ✅ PASS | 15s | |
| Web Fetch JSON | ✅ PASS | 8s | |
| Web Fetch HTML | ✅ PASS | 9s | |
| Data Extraction | ✅ PASS | 7s | |
| Multi-Step Reasoning | ✅ PASS | 7s | |
| Instruction Following | ✅ PASS | 6s | |
| Reasoning Tag Stripping | ✅ PASS | 5s | |
| Error Handling | ✅ PASS | 6s | |
| Consecutive Tools | ✅ PASS | 9s | |
| Skill Installation | ✅ PASS | 3s | |
| Muse Extension | ✅ PASS | 17s | |
| Shell Execution (exec) | ✅ PASS | 7s | |
| Web Search | ✅ PASS | 14s | Feature not configured |
| Browser Automation | ✅ PASS | 9s | Feature not configured |
| File Operations | ✅ PASS | 7s | |
| Sub-agent Communication | ✅ PASS | 7s | |
| Background Process | ❌ FAIL | 6s | Intermittent SSH timing issue |
| Image Analysis | ✅ PASS | 9s | Feature not configured |
| Session Status | ✅ PASS | 9s | |
| Multi-turn Context | ✅ PASS | 14s | |
| Research Task | ✅ PASS | 12s | |
| Code Generation | ✅ PASS | 8s | |
| Memory Operations | ✅ PASS | 17s | |
| Skill Workflow (weather) | ✅ PASS | 15s | |
| Multi-tool Chain | ✅ PASS | 13s | |
| Response Quality | ✅ PASS | 14s | |
| Error Recovery | ✅ PASS | 9s | |
| Complex Instructions | ✅ PASS | 12s | |
| Adversarial Input | ✅ PASS | 6s | |
| Long Context | ✅ PASS | 9s | |
| JSON Output | ✅ PASS | 8s | |

## Comparison to Other Models

| Aspect | Mistral Large 3 | Claude Opus 4.5 | Kimi K2 |
|--------|-----------------|-----------------|---------|
| Input Cost | $0.50/1M | $5.00/1M | $0.60/1M |
| Output Cost | $1.50/1M | $25.00/1M | $2.50/1M |
| Pass Rate | 97% | ~100%* | ~40% |
| Tool Use | Reliable | Reliable | Fails after calls |

*Claude Opus estimated - no benchmark report on file

## Notes

- Only 1 failure: TEST 18 (Background Process) - intermittent SSH timing issue, not a model limitation
- Cheaper than both Claude Opus and Kimi K2
- Strong tool use and context retention
- **Recommended as default model for cost-efficiency**

---
*Generated by claw-bench v1.3 - 2026-02-08*
